version: '3'
services:
  nats:
    image: nats:${NATS_VERSION}
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
      - '6222:6222'
    command: -js
    volumes:
      - './data/nats:/data'
