version: '3'
services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
      - './conf/dnsmasq.conf:/etc/dnsmasq.conf:ro'
