version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './conf/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './data/mysql:/var/lib/mysql'
      - './log/mysql:/var/log/mysql'
