version: '3'
services:
  emqx:
    image: emqx/emqx:${EMQX_VERSION}
    container_name: emqx
    ports:
      - '1883:1883'
      - '8083:8083'
      - '8084:8084'
      - '8883:8883'
      - '18083:18083'
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
    volumes:
      - './data/emqx:/opt/emqx/data'
      - './log/emqx:/opt/emqx/log'
