version: '3'

services:
  tomcat:
    image: tomcat:${TOMCAT_VERSION}
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./conf:/usr/local/tomcat/conf
      - ./logs:/usr/local/tomcat/logs
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
