version: '3'
services:
  namesrv:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-namesrv
    ports:
      - '9876:9876'
    command: sh mqnamesrv
    volumes:
      - './data/namesrv:/root/logs'
      - './log/namesrv:/root/logs'
  broker:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-broker
    ports:
      - '10911:10911'
      - '10909:10909'
    command: sh mqbroker -n namesrv:9876 -c /opt/rocketmq/conf/broker.conf
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - './data/broker:/root/store'
      - './log/broker:/root/logs'
      - './conf/broker.conf:/opt/rocketmq/conf/broker.conf'
    depends_on:
      - namesrv
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:${DASHBOARD_VERSION}
    container_name: rocketmq-dashboard
    ports:
      - '8080:8080'
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876
    depends_on:
      - namesrv
      - broker
