version: '3'
services:
  windows-arm:
    image: dockurr/windows
    container_name: windows-arm
    ports:
      - '8006:8006'
      - '3389:3389/tcp'
      - '3389:3389/udp'
    environment:
      - VERSION=${VERSION}
      - DISK_SIZE=${DISK_SIZE}
      - RAM_SIZE=${RAM_SIZE}
      - CPU_CORES=${CPU_CORES}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - LANGUAGE=${LANGUAGE}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - './data:/storage'
      - './shared:/shared'
    stop_grace_period: 2m
