version: '3'
services:
  vault:
    image: hashicorp/vault:${VAULT_VERSION}
    container_name: vault
    ports:
      - '8200:8200'
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - './data/vault:/vault/data'
    command: server -dev
