version: '3'
services:
  munin:
    image: dockurr/munin
    container_name: munin
    ports:
      - '8080:8080'
    volumes:
      - './data:/var/lib/munin'
      - './conf/munin.conf:/etc/munin/munin.conf:ro'
