version: '3'
services:
  zima:
    image: dockurr/zima
    container_name: zima
    ports:
      - '8080:8080'
    volumes:
      - './data:/DATA'
      - '/var/run/docker.sock:/var/run/docker.sock'
    stop_grace_period: 1m
