version: '3'
services:
  golang:
    image: golang:${GOLANG_VERSION}
    container_name: golang-app
    ports:
      - '8080:8080'
    volumes:
      - './conf:/go/src/app'
    working_dir: /go/src/app
    command: tail -f /dev/null
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: golang-mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './conf/my.cnf:/etc/mysql/conf.d/my.cnf'
  redis:
    image: redis:${REDIS_VERSION}
    container_name: golang-redis
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'
